### ISSUE TITLE
Swarm Spawn Camping

### ISSUE THREAD

**Issue by stickz** [Remscar/Morbus#11]
Humans keep camping in the swam spawn on maps like spaceship. Would it be a good idea to implement light attrition on humans; so, they can't camp for minutes in there?

**Comment by stickz** [comment]
Spawn protection for swarms would also be anther really good idea.

**Comment by Remscar** [comment]
I've personally never been opposed to humans camping the swarm spawn area, but in the instance of spaceship where humans can physically go inside of the spawn area, I don't feel the same way. I spawn protection timer might be a good idea or adjusting spaceship so that the aliens spawn in an inaccessible area.

**Comment by stickz** [comment]
The commit above resolves this issue by adding a spawn protection timer.
