### ISSUE TITLE
Swarm Fragging

### ISSUE THREAD

**Issue by makr6e6** [Remscar/Morbus#25]
If a player throws a grenade as human, suicides (or dies) before the explosion, and kills fellow humans. 
It will register as a swarm infect, creating broods and giving the player swarm points.
![swarmfragex](https://cloud.githubusercontent.com/assets/18020204/14102420/835ad8c2-f568-11e5-9005-49b2cbea805b.jpg)

**Comment by stickz** [comment]
I think the issue here is that the gamemode gets the clients current role when the frag grenade explodes. This doesn't account for that possibly of it changing between throwing and exploding time. 

If this is actually the case, it may be required to store the client's role in the entity class and account for this within the sv_player_damage.lua file when creating the damage info.

**Comment by makr6e6** [comment]
Redundant, but I tested this with props too and it works. Says Alex was turnt swarm, and he's brood.
![humansuicidepropinfect](https://cloud.githubusercontent.com/assets/18020204/14216552/7cc22da6-f817-11e5-83f9-1c1e5ab447ac.jpg)

**Comment by stickz** [comment]
I have fixed this issue by removing the grenade entity before it explodes, if the client is a swarm alien. Soon as I get a chance to package it, i'll create a pull request.
