### ISSUE TITLE
Max Ammo Needs Recoded

### ISSUE THREAD

**Issue by stickz** [Remscar/Morbus#42]
This should be inside the base class and inherited by each individual weapon. Not within the ammo entity code where less control is offered on a per-weapon basis. We're running into the problem with battery ammo for instance; where, the blaster has to use the same max ammo as the Teslar.

**Comment by Remscar** [comment]
The issue with having max ammo linked to what gun you are carrying means there will be a conflict if you carry two guns with the same ammo type, but different max ammo.

If the blaster is allowed to hold 40 ammo in reserve, and the Teslar only allows 10, what should be done if you have both? What happens when you drop the blaster? Do you lose 30 ammo, or do you keep it? How should this be explained/communicated to the player? 

If the issue only exists with battery based weapons, maybe batteries shouldn't be treated as 1 battery 1 shot like bullets are treated. The Teslar could cost 5 battery ammo per shot, or maybe the blaster could cost 1 battery ammo per two shots.

These are things I plan to address in Morbus 2

**Comment by stickz** [comment]
That makes a lot more sense adjusting the consumption on a per-weapon basis. Then communicating to the player the new max ammo they actually have. Thanks for the insight into a better solution!
